# Generated by Django 4.0.4 on 2022-07-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasbench201', '0004_nasbench201result_more_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasbench201result',
            name='res12',
        ),
        migrations.RemoveField(
            model_name='nasbench201result',
            name='res200',
        ),
    ]
